### ISSUE TITLE
希望能提供 16G 或 32G 内存的 Docker 安装

### ISSUE THREAD

**Issue by larryisthere** [analysys/argo-installer#20]
基于用户反馈，10% 左右的性能损失，及某些不稳定对于其生产环境来说是可容忍的。反而是由 8G 带来的服务被杀死的问题会更为严重。所以希望能提升 Docker 版的内存至 16g 及 32g。尤其是 16g。

**Comment by jiangzhx** [comment]
@zhaoy07331   我们16G 32G的 DOCKER应该部署好了，是否可以更新下链接地址。

**Comment by larryisthere** [comment]
@jiangzhx 文档我更新到这里了，直接可以拉取，改个参数就行。 
https://github.com/analysys/argo-installer/blob/master/INSTALL_DOCKER.md#%E6%8B%89%E5%8F%96%E9%95%9C%E5%83%8F

验证下没问题就 close 吧
