### ISSUE TITLE
希望能在 init_ext4.sh 中加入对最低安装环境的检测

### ISSUE THREAD

**Issue by larryisthere** [analysys/argo-installer#21]
目前很多同学依然会在个人电脑或者没有分配足够资源的虚拟机上进行安装
我们目前的安装流程不会因为环境不足进行提示或中断
而系统启动失败时也没有明确提示出相应原因
建议在安装部署的脚本中进行环境监测，至少是文字提示。
会极大提升自行安装成功的成功率。

**Comment by zhaoy07331** [comment]
挺好

**Comment by gaojun2048** [comment]
4.3.4版本已经加上。
