### ISSUE TITLE
使用离线下载模式也还是提示要配置config.properties地址

### ISSUE THREAD

**Issue by xiaoningz** [analysys/argo-installer#3]
使用离线下载模式也还是提示要配置config.properties地址
"请先配置config.properties文件中的源地址"

![image](https://user-images.githubusercontent.com/18545539/54585117-334e7980-4a54-11e9-8e90-cf817c30ab87.png)

**Comment by zhaoy07331** [comment]
We improved it

**Comment by jiangzhx** [comment]
fixed,checkout master branch.
