### ISSUE TITLE
权限管理能力

### ISSUE THREAD

**Issue by WUQUANLONG** [analysys/argo-installer#36]
具有一定保密性质的数据，能不能增加防止导出的能力？
同一个项目的多个分析人员，都能看到面板的分析结果和报表的时候，会不会出现，查看报表的人修改了分析和制作报表人的 已有报表？？？

**Comment by zhaoy07331** [comment]
查看报表的人，修改不了报表。报表主人才能修改

**Comment by zhaoy07331** [comment]
解决问题后，烦请close

**Comment by jiangzhx** [comment]
> 解决问题后，烦请close

可以满足客户需求吗？

@WUQUANLONG 
我们当前新的版本，可以基于profile表来控制权限。

**Comment by WUQUANLONG** [comment]
好的，感谢
