### ISSUE TITLE
项目管理里app已经集成sdk,debug模式数据已上传成功，但是还提示“未检测到数据，请集成后重新检测”

### ISSUE THREAD

**Issue by 17610178081** [analysys/argo-installer#38]
![image](https://user-images.githubusercontent.com/42194183/63011232-7fde9980-beba-11e9-8e3a-998432c583f4.png)
![image](https://user-images.githubusercontent.com/42194183/63011269-8ec54c00-beba-11e9-994c-d57a0fd4e762.png)

**Comment by jiangzhx** [comment]
通常这种情况，是因为hive服务没有启动。
建议在ambari后台观察下，服务是否运行正常。

**Comment by gaojun2048** [comment]
argo的数据收上来后是先写入kafka的，debug数据里看到的都是kafka里的数据。
然后kafka里的数据会经过项目的实时流处理程序处理并入库，入库之后的数据才能在系统里查询。
所以debug里有数，但还是未检测到数据，不能查询数据，说明可能项目实时流没有启动。请先检查项目的实时流是否已启动。

**Comment by gaojun2048** [comment]
@17610178081  请问问题是否已经解决？如果解决了，我就把issue关掉啦

**Comment by 17610178081** [comment]
已经解决了，关了吧




------------------ 原始邮件 ------------------
发件人: "gaojun2048"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 下午3:08
收件人: "analysys/argo-installer"<argo-installer@noreply.github.com>; 
抄送: "1435675149"<1435675149@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [analysys/argo-installer] 项目管理里app已经集成sdk,debug模式数据已上传成功，但是还提示“未检测到数据，请集成后重新检测” (#38)




@17610178081  请问问题是否已经解决？如果解决了，我就把issue关掉啦
