### ISSUE TITLE
能否提供基于 docker 的安装及部署方式

### ISSUE THREAD

**Issue by wwfalcon** [analysys/argo-installer#4]
从使用者角度，会更方便 😄

**Comment by gaojun416** [comment]
目前易观方舟Argo暂时不支持Docker部署，主要基于以下几点考虑:

目前Docker对于各个大数据组件各个版本的支持在兼容性、稳定性以及数据安全方面上还存在很多问题，社区也没有太多的技术支持。因此刚刚推出的易观方舟Argo版目前还不支持Docker部署。
易观方舟Agro主要聚焦点还是想让用户先用较低配的服务器把数据采集、存储、处理、查询访问的小闭环跑起来。尽量避免因Docker部署带来服务器成本的提高。
对于刚刚推出的易观方舟Argo，我们也希望通过直接部署的方式，让更多的技术人员能对易观方舟Argo的底层组件结构有更好的认识，给我们的后续优化迭代提出更多宝贵意见。

当然，提高易观方舟Argo实施部署的易用性也是目前方舟团队正在努力的目标。
后续我们会陆续推出基于阿里云、AWS的易观方舟Argo安装镜像包。同时也会升级易观方舟Argo的底层组件和Docker进行更好的融合。

针对实施部署这块，也希望更多的大数据技术爱好者与我们的技术团队一起探讨。

**Comment by wwfalcon** [comment]
了解，谢谢 😄
