### ISSUE TITLE
DataNode服务无法启动，报错信息：'/var/lib' is world-writable. Its permissions are 0777. 

### ISSUE THREAD

**Issue by mzhouliqun** [analysys/argo-installer#50]
发现DataNode服务关闭了，手动启动服务无效，报错信息如下：
![image](https://user-images.githubusercontent.com/33276792/63568771-0ffe9c00-c5a9-11e9-8fce-bafe42dd68c3.png)

**Comment by gaojun2048** [comment]
我看了下我们系统上/var/lib目录的权限是0755
drwxr-xr-x. 41 root root 4096 Aug 21 10:07 lib
你需要把你系统上这个目录的权限也改成0755才行。

**Comment by gaojun2048** [comment]
问题解决，关闭issue
