### ISSUE TITLE
run install sh script, Nothing to do 

### ISSUE THREAD

**Issue by larrychao** [analysys/argo-installer#68]
Hi.
   I run standalone_remote_installer.sh
   and log as follows, what's the error:
![image](https://user-images.githubusercontent.com/18112425/66448634-bd0f7400-ea84-11e9-8630-828e115996cf.png)

**Comment by jiangzhx** [comment]
你可以尝试把安装包，下载到本地，然后在本地安装。稳定性会好很多

**Comment by larrychao** [comment]
其实我之前是下载到本地的，但是解压包直接失败了，解压失败的包的名称是：analysys_installer_base_centos7.tar.gz

**Comment by larrychao** [comment]
原因是init_ext4.sh中存在脚本在本地执行异常，但有没有报错，手动执行就可以了

**Comment by jiangzhx** [comment]
@larrychao 问题解决了吗？如果解决了，我就关闭issue了
