### ISSUE TITLE
小版本在线/离线升级报错

### ISSUE THREAD

**Issue by qiudxx** [analysys/argo-installer#97]
1. 服务器配置信息
![image](https://user-images.githubusercontent.com/24288438/77729834-8e895380-703a-11ea-8589-7c1757a79770.png)

[](url)

2. 4.6.0071.  -->. 4.6.0079升级
![image](https://user-images.githubusercontent.com/24288438/77729237-21c18980-7039-11ea-9fd9-6633c48fd78f.png)

**Comment by wentome** [comment]
1. 在家目录执行操作试试

**Comment by qiudxx** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/24288438/77744506-aa99ee80-7054-11ea-8206-89d86887f827.png">

**Comment by qiudxx** [comment]
还是不行

**Comment by qiudxx** [comment]
> 1. 在家目录执行操作试试

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/24288438/77744842-327ff880-7055-11ea-8ebf-81ae94d2b7f8.png">

**Comment by wentome** [comment]
1.argo的家目录~   （/home/argo）
2.你这个免密好像不太对，解决方法，手动排查免密argo: ssh ark1 登录情况，如果有问题手动打通argo的免密

**Comment by qiudxx** [comment]
> 1.argo的家目录~ （/home/argo）
> 2.你这个免密好像不太对，解决方法，手动排查免密argo: ssh ark1 登录情况，如果有问题手动打通argo的免密



> 1.argo的家目录~ （/home/argo）
> 2.你这个免密好像不太对，解决方法，手动排查免密argo: ssh ark1 登录情况，如果有问题手动打通argo的免密
如何手动打通argo的免密？

**Comment by gaojun2048** [comment]
在机器上使用root用户执行：
1、生成key
```
ssh-keygen -t rsa
```
一路回车就行

2、打通免密
执行
```
ssh-coyp-id -i ark1
```
3、测试一下
```
su - argo
ssh ark1
```
如果出现要求输入yes/no，输入yes即可。
