### ISSUE TITLE
ARK web 启动失败

### ISSUE THREAD

**Issue by jitangshaobing** [analysys/argo-installer#99]
请问下，我ark web起不来是因为9090这个端口的服务，查了一下，本地没有服务占用9090，请问下这是哪个服务？
![image](https://user-images.githubusercontent.com/13791128/80300678-5f990580-87d1-11ea-8f7c-229a26bcebc1.png)

**Comment by gaojun2048** [comment]
9090就是ark web的监听端口，你看到的这个是监控告警，意思是连不上9090这个端口，说明ark web没起来。可以重试一下。
